{% set catalog_schema_table=source("atrixcore", "tblclients") %}
{% set partition_column="id" %}
{% set order_column="updated_at" %}

WITH latest AS (
  {{ dynamic_table_query(catalog_schema_table, partition_column, order_column) }}
),

transformed AS (
  SELECT
 accountmainid,
 accountmodelid,
 acquisition,
 address1,
 address2,
 allow_sso,
 authdata,
 authmodule,
 bankacct,
 bankcode,
 bankname,
 banktype,
 billingaddress,
 billingautomatic,
 billingcid,
 billingcity,
 billingcomplement,
 billingneighbor,
 billingnumber,
 billingpostcode,
 billingstate,
 cardlastfour,
 cardnum,
 cardtype,
 carnetgeneration,
 carnetgenerationbkp,
 city,
 cityid,
 classification,
 collectionpartnerid,
 companyname,
 complement,
 contractaccept,
 contractid,
 contractstage,
 country,
TRY_CAST(created_at AS DATE) AS created_at,
 credit,
 currency,
 TRY_CAST(dateborn AS DATE) AS dateborn,
 TRY_CAST(datecreated AS DATE) AS datecreated,
 defaultgateway,
 disableautocc,
 dlin,
 document,
 email,
 email2,
 email_verified,
 emailcount,
 emailoptout,
 erpid,
 expdate,
 filepath,
 firstname,
 fiscaladdress,
 fiscalcity,
 fiscalcomplement,
 fiscalneighbor,
 fiscalnumber,
 fiscalpostcode,
 fiscalstate,
 gatewayid,
 groupid,
 has_privacy_policy,
 hascredit,
 host,
 howourmeetid,
 id,
 id_integrator,
 idcondominium,
 imgprofile,
 integrated,
 integratedlivefc,
 ip,
 ismatriz,
 isprovider,
 issuenumber,
 language,
 lastlogin,
 lastname,
 lastupdateerp,
 latefeeoveride,
 legacyid,
 legacysystem,
 livefcmailsent,
 mailinvalid,
 manageraccount,
 namefather,
 namemother,
 nameprovider,
 noteinsidemonth,
 notes,
 number,
 opening_hours,
 overideduenotices,
 overrideautoclose,
 password,
 phonenumber,
 phonenumber2,
 postcode,
 postponedInvoiceMonth,
 premium,
 previousdaybilling,
 print_invoice,
 priority,
 prospect,
 pwresetexpiry,
 pwresetkey,
 receivemethodid,
 recovery_token,
 reference,
 registration_county,
 registration_state,
 remessa_migracao,
 rg,
 room,
 rownum1,
 rownum2,
 sapid,
 securityqans,
 securityqid,
 segmentid,
 sendemailcrm,
 separateinvoices,
 spc_serasa,
 TRY_CAST(startdate AS DATE) AS startdate,
 state,
 status,
 supportexclusive,
 taxexempt,
 typeaddress,
 typeclient,
TRY_CAST(updated_at AS DATE) AS updated_at,
 uuid,
 waysign,
 whatsapp_phone 

  FROM latest
)

SELECT *
FROM transformed
