SELECT 
  id_sydle_one AS codigo_sydle_one,
  nome_aprovacao,
  status_aprovacao,
  nome_aprovador_final_da_venda,
  executor_aprovacao,
  data_atendimento,
  data_conclusao,
  duracao_total,
  duracao_atendimento,
  canal_venda,
  data_criacao,
  data_venda,
  aprovado_pela_auditoria AS flag_aprovado_auditoria,
  venda_refeita AS flag_venda_refeita,
  justificativa_aprovacao,
  justificativa_aprovacao_id_sydle_one,
  status_processo,
  analise_financeira,
  id_prospecto AS codigo_prospecto,
  prospecto,
  endereco_instalacao_estado,
  endereco_instalacao_cidade,
  endereco_instalacao_bairro,
  endereco_instalacao_logradouro,
  endereco_instalacao_numero,
  oferta_selecionada,
  parceiro,
  responsavel_pela_venda_id_sydle_one AS codigo_sydle_responsavel_venda,
  responsavel_pela_venda_nome AS nome_reponsavel_venda,
  condominio_nome AS nome_condominio,
  condominio_id_sydle_one AS codigo_sydle_condominio,
  cpf,
  cnpj,
  contrato_codigo AS codigo_contrato,
  status_venda,
  resultado_analise_financeira_valor_maximo_restricoes_spc_soma,
  resultado_analise_financeira_quantidade_maxima_restricoes_spc,
  resultado_analise_financeira_aprovado_serasa,
  resultado_analise_financeira_classificacao_minima_serasa,
  regional_nome AS nome_regional,
  regional_id_sydle_one AS codigo_sydle_regional,
  telefone_utilizado_na_venda,
  air_codigo_contrato AS codigo_contrato_air,
  responsavel_analise_financeira_interna_nome AS nome_responsavel_analise_financeira_interna,
  responsavel_analise_financeira_interna_id_sydle_one AS codigo_sydle_responsavel_analise_financeira_interna,
  responsavel_analise_financeira_externa_nome AS nome_responsavel_analise_financeira_externa,
  responsavel_analise_financeira_externa_id_sydle_one AS codigo_sydle_responsavel_analise_financeira_externa,
  responsavel_analise_tecnica_nome AS nome_responsavel_analise_tecnica,
  responsavel_analise_tecnica_id_sydle_one AS codigo_sydle_responsavel_analise_tecnica,
  marca_associada,
  unidade_nome AS nome_unidade,
  unidade_sigla AS sigla_unidade,
  motivo_auditoria_qualify,
  valor_total_mensalidade_com_desconto,
  data_ativacao,
  data_integracao,
  data_extracao,
  date_sub(current_date(), 1) AS data_referencia
FROM {{ get_catalogo('gold') }}.sydle.dim_venda_qualify_vendedor