models:
  - name: vw_air_cupom
    columns:
      - name: id_cliente
        data_type: long 
      - name: cupom
        data_type: string 

  - name: vw_air_extracao
    columns:
      - name: data_criacao
        data_type: string 
      - name: id_contrato_air
        data_type: long 
      - name: equipe
        data_type: string 
      - name: canal
        data_type: string 
      - name: valor_final
        data_type: double 
      - name: fonte
        data_type: string 
      - name: marca
        data_type: string 
      - name: regional
        data_type: string 
      - name: legado_id
        data_type: long 
      - name: legado_sistema
        data_type: string 
      - name: cidade
        data_type: string 
      - name: estado
        data_type: string 
      - name: segmento
        data_type: string 
      - name: data_extracao
        data_type: timestamp_ntz 
