models:
  - name: tbl_contatos_mailing
    description: "Tabela dos contatos dos cliente formatada para o mailing de cobrança"
    columns:
      - name: id_cliente
        description: "ID de identificação do cliente"
        data_type: long
      - name: tel_01
        description: "Número de telefone em ordem de criação"
        data_type: string
      - name: tel_02
        description: "Número de telefone em ordem de criação"
        data_type: string
      - name: tel_03
        description: "Número de telefone em ordem de criação"
        data_type: string
      - name: tel_04
        description: "Número de telefone em ordem de criação"
        data_type: string
      - name: tel_05
        description: "Número de telefone em ordem de criação"
        data_type: string
      - name: tel_06
        description: "Número de telefone em ordem de criação"
        data_type: string
      - name: whatsapp
        description: "Número de whatsapp do cliente"
        data_type: string
      - name: sms
        description: "Número de sms do cliente"
        data_type: string
      - name: email
        description: "Endereço de E-mail do cliente"
        data_type: string