SELECT id_contrato as codigo_contrato_sydle,
      codigo_externo as codigo_contrato_air,
      plano_nome as nome_plano, 
      plano_identificador as codigo_plano, 
      forma_pagamento_grupo_forma_pagamento as forma_pagamento, 
      endereco_entrega_cidade_nome as cidade,
      endereco_entrega_estado_sigla as estado,
      dados_cobranca_dia_faturamento as dia_faturamento,
      dados_cobranca_dia_vencimento as dia_vencimento,
      status_status_servico as status_servico,
      status_data_status_faturamento as status_faturamento,
      status_data_status_financeiro as status_financeiro,
      data_venda,
      data_ativacao,
      tag,
      dados_suspensao_regra_suspensao as regra_suspensao,
      dados_suspensao_apto_suspensao as apto_suspensao,
      dados_suspensao_data_aptidao as data_aptidao,
      dados_suspensao_inserido_blacklist as inserido_blacklist,
      saldo_habilitacao_confianca_valor_saldo_atual as saldo_habilitacao_confianca,
      saldo_habilitacao_confianca_data_ultima_renovacao as data_ultima_renovacao,
      saldo_habilitacao_confianca_data_ultima_habilitacao_confianca as data_ultima_habilitacao_confianca
from {{ get_catalogo('gold') }}.sydle.dim_contrato_sydle
