models:
  - name: comparacao_contratos
    description: |
      Esta modelagem compara contratos antigos e novos,
      verificando dados como cancelamento, ativação e endereço. 
      Inclui métricas como tempo entre cancelamento e ativação, 
      e valida informações de CEP e número da residência para identificar possíveis inconsistências.
    columns:
      - name: codigo_contrato_antigo
        description: ID do contrato antigo.
        data_type: long
      - name: marca
        description: Marca associada ao contrato.
        data_type: string
      - name: codigo_contrato_novo
        description: ID do contrato novo.
        data_type: long
      - name: codigo_cliente
        description: ID do cliente.
        data_type: long
      - name: data_cancelamento_antigo
        description: Data de cancelamento do contrato antigo.
        data_type: date
      - name: data_venda_novo
        description: Data de venda do contrato novo.
        data_type: date
      - name: data_ativacao_novo
        description: Data de ativação do contrato novo.
        data_type: date
      - name: tempo_cancelamento_ativacao
        description: Tempo entre o cancelamento do contrato antigo e a ativação do contrato novo em dias.
        data_type: int
      - name: cep_antigo
        description: CEP do endereço antigo.
        data_type: string
      - name: cep_novo
        description: CEP do endereço novo.
        data_type: string
      - name: numero_residencia_antigo
        description: Número da residência do endereço antigo.
        data_type: string
      - name: numero_residencia_novo
        description: Número da residência do endereço novo.
        data_type: string
      - name: canal
        description: Canal tratado da venda.
        data_type: string
      - name: equipe
        description: Equipe responsável pela venda.
        data_type: string
      - name: email_vendedor
        description: Email do vendedor.
        data_type: string
      - name: cidade
        description: Cidade do endereço antigo.
        data_type: string
